In [29]:
import pandas as pd
bond=pd.read_csv("jamesbond.csv")
bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [30]:
bond.set_index(keys="Film", inplace=True)

In [31]:
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [32]:
bond.reset_index(inplace=True, drop=False)
bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [33]:
bond.set_index("Year")

,Film,Actor,Director,Box Office,Budget,Bond Actor Salary
Year,,,,,,
1962,Dr. No,Sean Connery,Terence Young,448.8,7.0,0.6
1963,From Russia with Love,Sean Connery,Terence Young,543.8,12.6,1.6
1964,Goldfinger,Sean Connery,Guy Hamilton,820.4,18.6,3.2
1965,Thunderball,Sean Connery,Terence Young,848.1,41.9,4.7
1967,Casino Royale,David Niven,Ken Hughes,315.0,85.0,NaN
1967,You Only Live Twice,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
1969,On Her Majesty's Secret Service,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
1971,Diamonds Are Forever,Sean Connery,Guy Hamilton,442.5,34.7,5.8
1973,Live and Let Die,Roger Moore,Guy Hamilton,460.3,30.8,NaN
1974,The Man with the Golden Gun,Roger Moore,Guy Hamilton,334.0,27.7,NaN
1977,The Spy Who Loved Me,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
1979,Moonraker,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
1981,For Your Eyes Only,Roger Moore,John Glen,449.4,60.2,NaN
1983,Never Say Never Again,Sean Connery,Irvin Kershner,380.0,86.0,NaN
1983,Octopussy,Roger Moore,John Glen,373.8,53.9,7.8
1985,A View to a Kill,Roger Moore,John Glen,275.2,54.5,9.1
1987,The Living Daylights,Timothy Dalton,John Glen,313.5,68.8,5.2
1989,Licence to Kill,Timothy Dalton,John Glen,250.9,56.7,7.9
1995,GoldenEye,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
1997,Tomorrow Never Dies,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
1999,The World Is Not Enough,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
2002,Die Another Day,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
2006,Casino Royale,Daniel Craig,Martin Campbell,581.5,145.3,3.3
2008,Quantum of Solace,Daniel Craig,Marc Forster,514.2,181.4,8.1
2012,Skyfall,Daniel Craig,Sam Mendes,943.5,170.2,14.5
2015,Spectre,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [37]:
bond.reset_index(drop=True)

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [39]:
bond.set_index("Year", inplace=True)

KeyError: "None of ['Year'] are in the columns"

In [40]:
bond.head()

,Film,Actor,Director,Box Office,Budget,Bond Actor Salary
Year,,,,,,
1962,Dr. No,Sean Connery,Terence Young,448.8,7.0,0.6
1963,From Russia with Love,Sean Connery,Terence Young,543.8,12.6,1.6
1964,Goldfinger,Sean Connery,Guy Hamilton,820.4,18.6,3.2
1965,Thunderball,Sean Connery,Terence Young,848.1,41.9,4.7
1967,Casino Royale,David Niven,Ken Hughes,315.0,85.0,NaN

In [42]:
bond.reset_index(drop=True)

,Film,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,Live and Let Die,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,The Man with the Golden Gun,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,The Spy Who Loved Me,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,Moonraker,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,For Your Eyes Only,Roger Moore,John Glen,449.4,60.2,NaN
13,Never Say Never Again,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,Roger Moore,John Glen,373.8,53.9,7.8
15,A View to a Kill,Roger Moore,John Glen,275.2,54.5,9.1
16,The Living Daylights,Timothy Dalton,John Glen,313.5,68.8,5.2
17,Licence to Kill,Timothy Dalton,John Glen,250.9,56.7,7.9
18,GoldenEye,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,Tomorrow Never Dies,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,The World Is Not Enough,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [43]:
bond.reset_index(drop=False)

,Year,Film,Actor,Director,Box Office,Budget,Bond Actor Salary
0,1962,Dr. No,Sean Connery,Terence Young,448.8,7.0,0.6
1,1963,From Russia with Love,Sean Connery,Terence Young,543.8,12.6,1.6
2,1964,Goldfinger,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,1965,Thunderball,Sean Connery,Terence Young,848.1,41.9,4.7
4,1967,Casino Royale,David Niven,Ken Hughes,315.0,85.0,NaN
5,1967,You Only Live Twice,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,1969,On Her Majesty's Secret Service,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,1971,Diamonds Are Forever,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,1973,Live and Let Die,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,1974,The Man with the Golden Gun,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,1977,The Spy Who Loved Me,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,1979,Moonraker,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,1981,For Your Eyes Only,Roger Moore,John Glen,449.4,60.2,NaN
13,1983,Never Say Never Again,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,1983,Octopussy,Roger Moore,John Glen,373.8,53.9,7.8
15,1985,A View to a Kill,Roger Moore,John Glen,275.2,54.5,9.1
16,1987,The Living Daylights,Timothy Dalton,John Glen,313.5,68.8,5.2
17,1989,Licence to Kill,Timothy Dalton,John Glen,250.9,56.7,7.9
18,1995,GoldenEye,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,1997,Tomorrow Never Dies,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,1999,The World Is Not Enough,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,2002,Die Another Day,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,2006,Casino Royale,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,2008,Quantum of Solace,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,2012,Skyfall,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,2015,Spectre,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [48]:
bond.reset_index(drop=True)

,Film,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,Live and Let Die,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,The Man with the Golden Gun,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,The Spy Who Loved Me,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,Moonraker,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,For Your Eyes Only,Roger Moore,John Glen,449.4,60.2,NaN
13,Never Say Never Again,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,Roger Moore,John Glen,373.8,53.9,7.8
15,A View to a Kill,Roger Moore,John Glen,275.2,54.5,9.1
16,The Living Daylights,Timothy Dalton,John Glen,313.5,68.8,5.2
17,Licence to Kill,Timothy Dalton,John Glen,250.9,56.7,7.9
18,GoldenEye,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,Tomorrow Never Dies,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,The World Is Not Enough,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [52]:
bond.set_index("Film")

,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,
Dr. No,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,David Niven,Ken Hughes,315.0,85.0,NaN
You Only Live Twice,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Diamonds Are Forever,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,Roger Moore,Guy Hamilton,460.3,30.8,NaN
The Man with the Golden Gun,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Moonraker,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
For Your Eyes Only,Roger Moore,John Glen,449.4,60.2,NaN
Never Say Never Again,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,Roger Moore,John Glen,373.8,53.9,7.8
A View to a Kill,Roger Moore,John Glen,275.2,54.5,9.1
The Living Daylights,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,Timothy Dalton,John Glen,250.9,56.7,7.9
GoldenEye,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Tomorrow Never Dies,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
The World Is Not Enough,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Casino Royale,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Quantum of Solace,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [58]:
bond.reset_index(drop=False, inplace=True)

In [59]:
bond.set_index("Film")

,index,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,,
Dr. No,0,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,2,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,3,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,4,1967,David Niven,Ken Hughes,315.0,85.0,NaN
You Only Live Twice,5,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,6,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Diamonds Are Forever,7,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,8,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
The Man with the Golden Gun,9,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,10,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Moonraker,11,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
For Your Eyes Only,12,1981,Roger Moore,John Glen,449.4,60.2,NaN
Never Say Never Again,13,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,14,1983,Roger Moore,John Glen,373.8,53.9,7.8
A View to a Kill,15,1985,Roger Moore,John Glen,275.2,54.5,9.1
The Living Daylights,16,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,17,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
GoldenEye,18,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Tomorrow Never Dies,19,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
The World Is Not Enough,20,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,21,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Casino Royale,22,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Quantum of Solace,23,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,24,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,25,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN